/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'George' at '9/16/16 10:33 PM' with Gradle 3.0
 *
 * @author George, @date 9/16/16 10:33 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
