/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'George' at '9/16/16 10:33 PM' with Gradle 3.0
 *
 * @author George, @date 9/16/16 10:33 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
